find_package( Qt5 COMPONENTS Widgets REQUIRED )

if( BUILD_GEODESIC_TRAINING )
  FIND_PACKAGE( ITK REQUIRED )
  SET(ITK_NO_IO_FACTORY_REGISTER_MANAGER "OFF")
  INCLUDE( ${ITK_USE_FILE} )
  FIND_PACKAGE( OpenCV REQUIRED )
endif( BUILD_GEODESIC_TRAINING )